### ISSUE TITLE
Bug -- login with google crashes

### ISSUE THREAD

**Issue by CircuitSacul** [SaptakBhoumik/WebPlus#7]
To reproduce:
 1. go to https://google.com in the WebPlus browser
 2. Hit the "login" button
 3. The browser crashes

I just pulled the latest code, and I'm running macOS

**Comment by SaptakBhoumik** [comment]
This is not a bug. If Google doesn't give us the permission then you can't login. However you can login to other websites

**Comment by CircuitSacul** [comment]
But is the browser supposed to crash?

**Comment by SaptakBhoumik** [comment]
> But is the browser supposed to crash?

It didn't crash when I tried

**Comment by SaptakBhoumik** [comment]
@CircuitSacul  You should get something like this 
![Untitled](https://user-images.githubusercontent.com/74509281/116422137-11439a00-a85d-11eb-88c7-ace074a05bd0.png)

**Comment by CircuitSacul** [comment]
<img width="521" alt="Screen Shot 2021-04-28 at 10 37 52 AM" src="https://user-images.githubusercontent.com/55721663/116422479-cb131a00-a80d-11eb-86cb-03b2598115b6.png">
I just get this

**Comment by SaptakBhoumik** [comment]
Try again after restarting your computer because this is not supposed to happen

**Comment by SaptakBhoumik** [comment]
Did it work?

**Comment by CircuitSacul** [comment]
I'll let you know when I have a chance to try it

**Comment by SaptakBhoumik** [comment]
Ok

**Comment by SaptakBhoumik** [comment]
Did it work?
